server:
  port: 8081

spring:
  application:
    name: solrAppTest
  data:
    solr:
      host: http://localhost:8080/solr/collection1    #指定具体的Core
      repositories:
        enabled: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/myfinaltest?serverTimezone=GMT

  thymeleaf:
    prefix: classpath:/static/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false



